### ISSUE TITLE
Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by shellscape** [unjs/unpdf#8]
### Environment

 System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 89.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

### Reproduction

Using the exact code snippet from the README for `renderPageAsImage`

### Describe the bug

```
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /Users/code/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/bindings.js
- /Users/code/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/canvas.js
- /Users/code/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at a._resolveFilename (/Users/powella/Library/pnpm/global/5/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/code/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.S (/Users/powella/Library/pnpm/global/5/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/code/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/bindings.js',
    '/Users/code/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/lib/canvas.js',
    '/Users/code/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/index.js'
  ]
}

Node.js v18.15.0
```

**Comment by johannschopplich** [comment]
That's not an issue of unpdf, but the `node-canvas` package itself.
For reference: https://github.com/Automattic/node-canvas/issues/2135
